[project]
name = "TelegramBot"
version = "0.1.0"
description = "MoveBro Telegram bot"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core", "aiogram", "sqlalchemy", "pydantic", "psycopg", "pydantic-settings", "aiogram_dialog"]